:output:
  Admin:
    :options:
      :fields:
      - id
      - username
      - email
      - type
      - encrypted_password
  Seller:
    :options:
      :fields:
      - id
      - username
      - email
      - type